// Auto-generated by hub-codegen
// Do not edit manually

import type { Forge } from '../../hyperforge/org/types';

export type ForgeEvent = ForgeEvent_ReposListed | ForgeEvent_RepoCreated | ForgeEvent_AuthStatus | ForgeEvent_ApiProgress | ForgeEvent_Error | ForgeEvent_AuthStarted | ForgeEvent_AuthResult | ForgeEvent_AuthFailed | ForgeEvent_RefreshStarted | ForgeEvent_RefreshComplete | ForgeEvent_RefreshFailed;

/** List of repositories on forge */
export interface ForgeEvent_ReposListed {
  type: 'repos_listed';
  forge: Forge;
  owner: string;
  repos: ForgeRepoSummary[];
}

/** Repository created on forge */
export interface ForgeEvent_RepoCreated {
  type: 'repo_created';
  forge: Forge;
  owner: string;
  repoName: string;
  url: string;
}

/** Authentication status */
export interface ForgeEvent_AuthStatus {
  type: 'auth_status';
  authenticated: boolean;
  forge: Forge;
  scopes: string[];
  user: string | null;
}

/** API call progress */
export interface ForgeEvent_ApiProgress {
  type: 'api_progress';
  forge: Forge;
  message: string;
  operation: string;
}

/** API error */
export interface ForgeEvent_Error {
  type: 'error';
  forge: Forge;
  message: string;
  operation: string;
  statusCode: number | null;
}

/** Auth check started */
export interface ForgeEvent_AuthStarted {
  type: 'auth_started';
  forge: Forge;
  orgName: string;
}

/** Auth check completed with result */
export interface ForgeEvent_AuthResult {
  type: 'auth_result';
  forge: Forge;
  lastValidated: string | null;
  orgName: string;
  scopes: string[];
  status: TokenStatus;
  username: string | null;
}

/** Auth check failed (network/internal error, not auth failure) */
export interface ForgeEvent_AuthFailed {
  type: 'auth_failed';
  error: string;
  forge: Forge;
  orgName: string;
}

/** Token refresh started */
export interface ForgeEvent_RefreshStarted {
  type: 'refresh_started';
  forge: Forge;
  orgName: string;
}

/** Token refresh completed successfully */
export interface ForgeEvent_RefreshComplete {
  type: 'refresh_complete';
  forge: Forge;
  orgName: string;
  status: TokenStatus;
}

/** Token refresh failed */
export interface ForgeEvent_RefreshFailed {
  type: 'refresh_failed';
  error: string;
  forge: Forge;
  orgName: string;
}


/** Summary of a repository on a forge */
export interface ForgeRepoSummary {
  description?: string | null;
  name: string;
  private: boolean;
  url: string;
}

/** Status of a token for a specific org/forge combination */
export type TokenStatus = never;

