// Auto-generated by hub-codegen
// Do not edit manually

/** Events from mustache operations */
export type MustacheEvent = MustacheEvent_Rendered | MustacheEvent_Registered | MustacheEvent_Template | MustacheEvent_NotFound | MustacheEvent_Templates | MustacheEvent_Deleted | MustacheEvent_Error;

/** Template rendered successfully */
export interface MustacheEvent_Rendered {
  type: 'rendered';
  /** The rendered output */
  output: string;
}

/** Template registered successfully */
export interface MustacheEvent_Registered {
  type: 'registered';
  /** Template info */
  template: TemplateInfo;
}

/** Template retrieved */
export interface MustacheEvent_Template {
  type: 'template';
  /** The template content */
  template: string;
}

/** Template not found */
export interface MustacheEvent_NotFound {
  type: 'not_found';
  /** Description of what was not found */
  message: string;
}

/** List of templates */
export interface MustacheEvent_Templates {
  type: 'templates';
  /** The templates */
  templates: TemplateInfo[];
}

/** Template deleted */
export interface MustacheEvent_Deleted {
  type: 'deleted';
  /** Number of templates deleted */
  count: number;
}

/** Error occurred */
export interface MustacheEvent_Error {
  type: 'error';
  /** Error message */
  message: string;
}


/** Information about a registered template */
export interface TemplateInfo {
  /** When the template was created (Unix timestamp) */
  createdAt: number;
  /** Unique template ID */
  id: string;
  /** Method this template is for */
  method: string;
  /** Template name (e.g., "default", "compact", "verbose") */
  name: string;
  /** Plugin that owns this template */
  pluginId: string;
  /** When the template was last updated (Unix timestamp) */
  updatedAt: number;
}
