// Auto-generated by hub-codegen
// Do not edit manually

/** Unique identifier for a single execution */
export type ExecutionId = string;

/** Events emitted during JavaScript execution */
export type JsExecEvent = JsExecEvent_ExecutionStarted | JsExecEvent_ExecutionCompleted | JsExecEvent_Console | JsExecEvent_Returned | JsExecEvent_FetchStarted | JsExecEvent_FetchCompleted | JsExecEvent_Error | JsExecEvent_ResourceWarning | JsExecEvent_ScriptStored | JsExecEvent_ScriptDeleted;

/** Execution has started */
export interface JsExecEvent_ExecutionStarted {
  type: 'execution_started';
  executionId: ExecutionId;
  scriptId: ScriptId | null;
  workerId: string;
}

/** Execution has completed successfully */
export interface JsExecEvent_ExecutionCompleted {
  type: 'execution_completed';
  executionId: ExecutionId;
  metrics: ResourceMetrics;
}

/** Console output from the script */
export interface JsExecEvent_Console {
  type: 'console';
  args: unknown[];
  level: LogLevel;
  timestampMs: number;
}

/** Script returned a value */
export interface JsExecEvent_Returned {
  type: 'returned';
  value: unknown;
}

/** A fetch request has started */
export interface JsExecEvent_FetchStarted {
  type: 'fetch_started';
  method: string;
  requestId: string;
  url: string;
}

/** A fetch request has completed */
export interface JsExecEvent_FetchCompleted {
  type: 'fetch_completed';
  durationMs: number;
  requestId: string;
  status: number;
}

/** An error occurred during execution */
export interface JsExecEvent_Error {
  type: 'error';
  location: SourceLocation | null;
  message: string;
  name: string;
  stack: StackFrame[];
}

/** Resource usage is approaching limits */
export interface JsExecEvent_ResourceWarning {
  type: 'resource_warning';
  current: number;
  limit: number;
  message: string;
  resource: string;
}

/** A script has been stored */
export interface JsExecEvent_ScriptStored {
  type: 'script_stored';
  hash: string;
  name: string;
  scriptId: ScriptId;
  sizeBytes: number;
}

/** A script has been deleted */
export interface JsExecEvent_ScriptDeleted {
  type: 'script_deleted';
  scriptId: ScriptId;
}


/** Log level for console output */
export type LogLevel = "log" | "info" | "warn" | "error" | "debug" | "trace";

/** Metrics collected during script execution */
export interface ResourceMetrics {
  /** CPU time consumed in milliseconds */
  cpuTimeMs: number;
  /** Peak memory usage in bytes */
  memoryPeakBytes: number;
  /** Current memory usage in bytes */
  memoryUsedBytes: number;
  /** Wall clock time elapsed in milliseconds */
  wallTimeMs: number;
}

/** Unique identifier for a stored script */
export type ScriptId = string;

/** Location within a script file */
export interface SourceLocation {
  /** Column number (1-indexed) */
  column: number;
  /** Filename if available */
  filename?: string | null;
  /** Line number (1-indexed) */
  line: number;
}

/** A single frame in a stack trace */
export interface StackFrame {
  /** Function name if available */
  functionName?: string | null;
  /** Source location of this frame */
  location: SourceLocation;
}

// === Stub Types (referenced but not defined in schema) ===

/** Stub type - definition missing from IR */
export type ScriptMetadata = unknown;
