// Auto-generated by hub-codegen
// Do not edit manually

/** A changelog entry documenting a plexus hash transition */
export interface ChangelogEntry {
  /** Who/what added this entry */
  author?: string | null;
  /** Unix timestamp when this entry was added */
  createdAt: number;
  /** Detailed list of changes (bullet points) */
  details?: string[];
  /** The plexus_hash this entry documents */
  hash: string;
  /** The previous hash this transitioned from (None for initial entry) */
  previousHash?: string | null;
  /** Reference to a queue item this changelog completes */
  queueId?: string | null;
  /** Short summary of changes (one line) */
  summary: string;
}

/** Events emitted by changelog operations */
export type ChangelogEvent = ChangelogEvent_EntryAdded | ChangelogEvent_Entries | ChangelogEvent_Status | ChangelogEvent_StartupCheck | ChangelogEvent_QueueAdded | ChangelogEvent_QueueUpdated | ChangelogEvent_QueueEntries | ChangelogEvent_QueueItem;

/** Entry was added */
export interface ChangelogEvent_EntryAdded {
  type: 'entry_added';
  entry: ChangelogEntry;
}

/** List of entries */
export interface ChangelogEvent_Entries {
  type: 'entries';
  entries: ChangelogEntry[];
}

/** Current state check result */
export interface ChangelogEvent_Status {
  type: 'status';
  currentHash: string;
  entry: ChangelogEntry | null;
  isDocumented: boolean;
  previousHash: string | null;
}

/** Startup check result */
export interface ChangelogEvent_StartupCheck {
  type: 'startup_check';
  currentHash: string;
  hashChanged: boolean;
  isDocumented: boolean;
  message: string;
  previousHash: string | null;
}

/** Queue item was added */
export interface ChangelogEvent_QueueAdded {
  type: 'queue_added';
  entry: QueueEntry;
}

/** Queue item was updated (e.g., marked complete) */
export interface ChangelogEvent_QueueUpdated {
  type: 'queue_updated';
  entry: QueueEntry;
}

/** List of queue items */
export interface ChangelogEvent_QueueEntries {
  type: 'queue_entries';
  entries: QueueEntry[];
}

/** Single queue item */
export interface ChangelogEvent_QueueItem {
  type: 'queue_item';
  entry: QueueEntry | null;
}


/** A queued change - a planned modification that systems should implement */
export interface QueueEntry {
  /** Unix timestamp when this was completed */
  completedAt?: number | null;
  /** The hash where this change was implemented (set when completed) */
  completedHash?: string | null;
  /** Unix timestamp when this was queued */
  createdAt: number;
  /** Description of the planned change */
  description: string;
  /** Unique identifier for this queue item */
  id: string;
  /** Current status of the queue item */
  status: QueueStatus;
  /** Tags to identify which systems this change affects (e.g., "frontend", "api", "breaking") */
  tags?: string[];
}

/** Status of a queued change */
export type QueueStatus = "pending" | "completed";
