// Auto-generated by hub-codegen
// Do not edit manually

export type Forge = "github" | "codeberg" | "gitlab";

/** Per-forge configuration options */
export interface ForgeConfig {
  /** Whether to sync repositories to this forge (default: true) */
  sync?: boolean;
}

/** Forges configuration that supports both legacy array format and new object format.

Legacy format (array of forge names):
```yaml
forges:
  - github
  - codeberg
```

New format (object with per-forge config):
```yaml
forges:
  github:
    sync: true
  codeberg:
    sync: false
``` */
export type ForgesConfig = unknown;

export interface Org {
  defaultVisibility: Visibility;
  /** Forges configuration - supports both legacy array format and new object format */
  forges: ForgesConfig;
  name: string;
  origin: Forge;
  owner: string;
  sshKey: string;
}

export type OrgEvent = OrgEvent_Listed | OrgEvent_Details | OrgEvent_Created | OrgEvent_Removed | OrgEvent_Updated | OrgEvent_Info | OrgEvent_ImportStarted | OrgEvent_RepoImported | OrgEvent_ImportComplete | OrgEvent_Error;

/** List of all organizations */
export interface OrgEvent_Listed {
  type: 'listed';
  orgs: OrgSummary[];
}

/** Details of a single organization */
export interface OrgEvent_Details {
  type: 'details';
  org: Org;
}

/** Organization created */
export interface OrgEvent_Created {
  type: 'created';
  orgName: string;
}

/** Organization removed */
export interface OrgEvent_Removed {
  type: 'removed';
  orgName: string;
}

/** Organization updated */
export interface OrgEvent_Updated {
  type: 'updated';
  field: string;
  orgName: string;
  value: string;
}

/** Informational message about organization */
export interface OrgEvent_Info {
  type: 'info';
  message: string;
  name: string;
}

/** Import started */
export interface OrgEvent_ImportStarted {
  type: 'import_started';
  forges: Forge[];
  orgName: string;
}

/** Repository discovered during import */
export interface OrgEvent_RepoImported {
  type: 'repo_imported';
  description: string | null;
  forges: Forge[];
  orgName: string;
  repoName: string;
  visibility: Visibility;
}

/** Import completed */
export interface OrgEvent_ImportComplete {
  type: 'import_complete';
  importedCount: number;
  orgName: string;
  skippedCount: number;
}

/** Error occurred */
export interface OrgEvent_Error {
  type: 'error';
  message: string;
}


export interface OrgSummary {
  forges: ForgesConfig;
  name: string;
  owner: string;
}

export type Visibility = "public" | "private";
