// Auto-generated by hub-codegen
// Do not edit manually

/** Summary of a child plugin */
export interface ChildSummary {
  /** Human-readable description */
  description: string;
  /** Content hash for cache invalidation */
  hash: string;
  /** The child's namespace */
  namespace: string;
}

/** Stream events from health check

This is a plain domain type - no trait implementations needed.
The caller (Plexus) wraps this with metadata when streaming. */
export type HealthEvent = HealthEvent_Status;

/** Current health status */
export interface HealthEvent_Status {
  type: 'status';
  status: string;
  timestamp: number;
  uptimeSeconds: number;
}


/** Schema for a single method exposed by a plugin */
export interface MethodSchema {
  /** Human-readable description of what this method does */
  description: string;
  /** Content hash of the method definition (for cache invalidation)
Generated by hashing the method signature within hub-macro */
  hash: string;
  /** Method name (e.g., "echo", "check") */
  name: string;
  /** JSON Schema for the method's parameters (None if no params) */
  params?: Schema | null;
  /** JSON Schema for the method's return type (None if not specified) */
  returns?: Schema | null;
  /** Whether this method streams multiple events (true) or returns a single result (false)

- `streaming: true` → returns `AsyncGenerator<T>` (multiple events)
- `streaming: false` → returns `Promise<T>` (single event, collected)

All methods use the same streaming protocol under the hood, but this flag
tells clients how to present the result. */
  streaming?: boolean;
}

/** A plugin's schema with methods and child summaries.

Children are represented as summaries (namespace, description, hash) rather
than full recursive schemas. This enables lazy traversal - clients can fetch
child schemas individually via `{namespace}.schema`.

- Leaf plugins have `children = None`
- Hub plugins have `children = Some([ChildSummary, ...])` */
export interface PluginSchema {
  /** Child plugin summaries (None = leaf plugin, Some = hub plugin) */
  children?: unknown[] | null;
  /** Short description of the plugin (max 15 words) */
  description: string;
  /** Content hash computed from methods + children hashes (for cache invalidation)
This hash changes when any method or child plugin changes */
  hash: string;
  /** Detailed description of the plugin (optional) */
  longDescription?: string | null;
  /** Methods exposed by this plugin */
  methods: MethodSchema[];
  /** The plugin's namespace (e.g., "echo", "plexus") */
  namespace: string;
  /** The plugin's version (e.g., "1.0.0") */
  version: string;
}

export type Schema = unknown;

// === Stub Types (referenced but not defined in schema) ===

/** Stub type - definition missing from IR */
export type SchemaResult = unknown;
