// Auto-generated by hub-codegen
// Do not edit manually

import type { Forge, Visibility } from '../../../../hyperforge/org/types';

/** Result of a convergence operation */
export interface ConvergeResult {
  /** Whether the system converged (no remaining drift) */
  converged: boolean;
  /** Whether drift was detected after apply */
  driftDetected: boolean;
  /** Number of repos created on forges */
  reposCreated: number;
  /** Number of repos deleted from forges */
  reposDeleted: number;
  /** Number of repos synced (created + updated) */
  reposSynced: number;
}

/** Status of a repository in a diff operation */
export type DiffStatus = "to_create" | "to_update" | "to_delete" | "in_sync" | "untracked";

export interface RepoDetails {
  description?: string | null;
  forgeUrls: Record<string, unknown>;
  name: string;
  visibility: Visibility;
}

export type RepoEvent = RepoEvent_Listed | RepoEvent_Details | RepoEvent_Staged | RepoEvent_Synced | RepoEvent_SyncStarted | RepoEvent_SyncProgress | RepoEvent_SyncComplete | RepoEvent_MarkedForDeletion | RepoEvent_ProtectionError | RepoEvent_Removed | RepoEvent_RemoteAdded | RepoEvent_RemotesValidated | RepoEvent_OutputsCaptured | RepoEvent_RefreshStarted | RepoEvent_RefreshProgress | RepoEvent_RefreshComplete | RepoEvent_RepoDiff | RepoEvent_DiffSummary | RepoEvent_ConvergeStarted | RepoEvent_ConvergePhase | RepoEvent_ConvergeComplete | RepoEvent_CloneStarted | RepoEvent_CloneProgress | RepoEvent_CloneRemoteAdded | RepoEvent_CloneComplete | RepoEvent_RemoteSyncStatus | RepoEvent_ForgeSkipped | RepoEvent_LocalInitialized | RepoEvent_GitignoreCreated | RepoEvent_LocalSetupComplete | RepoEvent_Error;

/** List of repositories */
export interface RepoEvent_Listed {
  type: 'listed';
  orgName: string;
  repos: RepoSummary[];
  staged: boolean;
}

/** Details of a single repository */
export interface RepoEvent_Details {
  type: 'details';
  orgName: string;
  repo: RepoDetails;
}

/** Repository staged for creation */
export interface RepoEvent_Staged {
  type: 'staged';
  orgName: string;
  repoName: string;
}

/** Repository created/synced on forge */
export interface RepoEvent_Synced {
  type: 'synced';
  forge: Forge;
  orgName: string;
  repoName: string;
  url: string;
}

/** Sync operation started */
export interface RepoEvent_SyncStarted {
  type: 'sync_started';
  orgName: string;
  repoCount: number;
}

/** Sync progress update */
export interface RepoEvent_SyncProgress {
  type: 'sync_progress';
  orgName: string;
  repoName: string;
  stage: string;
}

/** Sync operation completed */
export interface RepoEvent_SyncComplete {
  type: 'sync_complete';
  orgName: string;
  success: boolean;
  syncedCount: number;
}

/** Repository marked for deletion */
export interface RepoEvent_MarkedForDeletion {
  type: 'marked_for_deletion';
  orgName: string;
  repoName: string;
}

/** Repository protection error (protected repos require --force) */
export interface RepoEvent_ProtectionError {
  type: 'protection_error';
  message: string;
  orgName: string;
  repoName: string;
}

/** Repository removed */
export interface RepoEvent_Removed {
  type: 'removed';
  orgName: string;
  repoName: string;
}

/** Git remote added to local repository */
export interface RepoEvent_RemoteAdded {
  type: 'remote_added';
  orgName: string;
  remote: string;
  repoName: string;
  url: string;
}

/** Git remotes validated for a repository */
export interface RepoEvent_RemotesValidated {
  type: 'remotes_validated';
  orgName: string;
  remotes: string[];
  repoName: string;
}

/** Outputs captured from Pulumi after apply */
export interface RepoEvent_OutputsCaptured {
  type: 'outputs_captured';
  forge: Forge;
  id: string | null;
  orgName: string;
  repoName: string;
  url: string;
}

/** Refresh started - querying forges for remote state */
export interface RepoEvent_RefreshStarted {
  type: 'refresh_started';
  forges: Forge[];
  orgName: string;
}

/** Forge query progress during refresh */
export interface RepoEvent_RefreshProgress {
  type: 'refresh_progress';
  forge: Forge;
  orgName: string;
  reposFound: number;
}

/** Refresh completed with discovery statistics */
export interface RepoEvent_RefreshComplete {
  type: 'refresh_complete';
  discovered: number;
  matched: number;
  orgName: string;
  untracked: number;
}

/** Diff result for a single repository */
export interface RepoEvent_RepoDiff {
  type: 'repo_diff';
  details: string[];
  orgName: string;
  repoName: string;
  status: DiffStatus;
}

/** Overall diff summary for an organization */
export interface RepoEvent_DiffSummary {
  type: 'diff_summary';
  inSync: number;
  orgName: string;
  toCreate: number;
  toDelete: number;
  toUpdate: number;
  untracked: number;
}

/** Converge operation started */
export interface RepoEvent_ConvergeStarted {
  type: 'converge_started';
  orgName: string;
  phases: string[];
}

/** Converge phase status update */
export interface RepoEvent_ConvergePhase {
  type: 'converge_phase';
  orgName: string;
  phase: string;
  status: string;
}

/** Converge operation completed */
export interface RepoEvent_ConvergeComplete {
  type: 'converge_complete';
  changesApplied: number;
  finalState: ConvergeResult;
  orgName: string;
  success: boolean;
}

/** Clone operation started */
export interface RepoEvent_CloneStarted {
  type: 'clone_started';
  orgName: string;
  repoName: string;
  targetPath: string;
}

/** Clone progress - cloning from forge */
export interface RepoEvent_CloneProgress {
  type: 'clone_progress';
  forge: Forge;
  orgName: string;
  repoName: string;
  stage: string;
}

/** Remote added during clone */
export interface RepoEvent_CloneRemoteAdded {
  type: 'clone_remote_added';
  orgName: string;
  remoteName: string;
  repoName: string;
  url: string;
}

/** Clone completed successfully */
export interface RepoEvent_CloneComplete {
  type: 'clone_complete';
  orgName: string;
  remotes: string[];
  repoName: string;
  targetPath: string;
}

/** Remote sync status (comparing refs across remotes) */
export interface RepoEvent_RemoteSyncStatus {
  type: 'remote_sync_status';
  branch: string;
  details: string[];
  inSync: boolean;
  orgName: string;
  repoName: string;
}

/** Forge skipped due to sync flag being false */
export interface RepoEvent_ForgeSkipped {
  type: 'forge_skipped';
  forge: Forge;
  orgName: string;
  reason: string;
}

/** Local git repository initialized */
export interface RepoEvent_LocalInitialized {
  type: 'local_initialized';
  orgName: string;
  path: string;
  repoName: string;
}

/** .gitignore file created */
export interface RepoEvent_GitignoreCreated {
  type: 'gitignore_created';
  orgName: string;
  path: string;
  repoName: string;
}

/** Local repository setup complete (init + gitignore + remotes) */
export interface RepoEvent_LocalSetupComplete {
  type: 'local_setup_complete';
  orgName: string;
  path: string;
  repoName: string;
}

/** Error during repo operation */
export interface RepoEvent_Error {
  type: 'error';
  message: string;
  orgName: string;
  repoName: string | null;
}


export interface RepoSummary {
  forges: Forge[];
  name: string;
  synced: boolean;
  visibility: Visibility;
}
