// Auto-generated by hub-codegen
// Do not edit manually

// === Core Transport Types ===
// These types define the wire format for all plexus streaming responses.

/** Metadata applied by the caller when wrapping activation responses */
export interface StreamMetadata {
  /** Call path through the system (e.g., ["plexus", "health"]) */
  provenance: string[];
  /** Hash of plexus configuration for cache invalidation */
  plexusHash: string;
  /** Unix timestamp (seconds) when the event was wrapped */
  timestamp: number;
}

/** Universal stream item - all activations emit this type */
export type PlexusStreamItem =
  | PlexusStreamItem_Data
  | PlexusStreamItem_Progress
  | PlexusStreamItem_Error
  | PlexusStreamItem_Done;

/** Data payload with caller-applied metadata */
export interface PlexusStreamItem_Data {
  type: 'data';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Type identifier for deserialization (e.g., "health.status") */
  contentType: string;
  /** The actual payload (serialized activation event) */
  content: unknown;
}

/** Progress update during long-running operations */
export interface PlexusStreamItem_Progress {
  type: 'progress';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Human-readable progress message */
  message: string;
  /** Optional completion percentage (0.0 - 100.0) */
  percentage?: number;
}

/** Error occurred during processing */
export interface PlexusStreamItem_Error {
  type: 'error';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
  /** Human-readable error message */
  message: string;
  /** Optional error code for programmatic handling */
  code?: string;
  /** Whether the operation can be retried */
  recoverable: boolean;
}

/** Stream completed successfully */
export interface PlexusStreamItem_Done {
  type: 'done';
  /** Metadata from calling layer */
  metadata: StreamMetadata;
}

/** Error thrown when a PlexusStreamItem_Error is received */
export class PlexusError extends Error {
  constructor(
    message: string,
    public readonly code?: string,
    public readonly recoverable: boolean = false,
    public readonly metadata?: StreamMetadata
  ) {
    super(message);
    this.name = 'PlexusError';
  }
}


// Domain types are exported from their respective namespace modules
// Import as: import { TypeName } from './namespace/types'