// Auto-generated by hub-codegen
// Do not edit manually

export interface Capabilities {
  contextWindow: number;
  functions?: boolean;
  jsonMode?: boolean;
  maxOutputTokens: number;
  multimodal?: boolean;
  streaming?: boolean;
  systemPrompt?: boolean;
  vision?: boolean;
}

/** Events emitted during cone.chat (streaming) */
export type ChatEvent = ChatEvent_ChatStart | ChatEvent_ChatContent | ChatEvent_ChatComplete | ChatEvent_Error;

/** Chat response started */
export interface ChatEvent_ChatStart {
  type: 'chat_start';
  coneId: string;
  /** Position of the user message node */
  userPosition: Position;
}

/** Chat content chunk (streaming) */
export interface ChatEvent_ChatContent {
  type: 'chat_content';
  coneId: string;
  content: string;
}

/** Chat response complete */
export interface ChatEvent_ChatComplete {
  type: 'chat_complete';
  coneId: string;
  /** The new head position (tree + response node) */
  newHead: Position;
  /** Total tokens used (if available) */
  usage: ChatUsage | null;
}

export interface ChatEvent_Error {
  type: 'error';
  message: string;
}


/** Token usage information */
export interface ChatUsage {
  inputTokens?: number | null;
  outputTokens?: number | null;
  totalTokens?: number | null;
}

/** Cone configuration - defines an cone's identity and behavior */
export interface ConeConfig {
  /** Created timestamp */
  createdAt: number;
  /** The canonical head - current position in conversation tree
This couples tree_id and node_id together */
  head: Position;
  /** Unique identifier for this cone */
  id: string;
  /** Additional configuration metadata */
  metadata?: unknown;
  /** Model ID to use (e.g., "gpt-4o-mini", "claude-3-haiku-20240307") */
  modelId: string;
  /** Human-readable name */
  name: string;
  /** System prompt / instructions for the cone */
  systemPrompt?: string | null;
  /** Last updated timestamp */
  updatedAt: number;
}

/** Identifier for a cone - either by name or UUID

CLI usage: Just pass the name or UUID directly (e.g., "my-assistant" or "550e8400-...")
The CLI/API will handle the conversion to the appropriate lookup type. */
export type ConeIdentifier = ConeIdentifier_ByName | ConeIdentifier_ById;

/** Lookup cone by its human-readable name */
export interface ConeIdentifier_ByName {
  type: 'by_name';
  /** Cone name (supports partial matching, e.g., "assistant" or "assistant#550e") */
  name: string;
}

/** Lookup cone by its UUID */
export interface ConeIdentifier_ById {
  type: 'by_id';
  /** Cone UUID */
  id: string;
}


/** Lightweight cone info (for listing) */
export interface ConeInfo {
  createdAt: number;
  head: Position;
  id: string;
  modelId: string;
  name: string;
}

export interface Constraints {
  maxFunctionCallsPerMessage?: number | null;
  maxImageSizeMb?: number | null;
  maxImagesPerMessage?: number | null;
  supportedImageFormats?: string[];
}

/** Result of cone.create */
export type CreateResult = CreateResult_ConeCreated | CreateResult_Error;

export interface CreateResult_ConeCreated {
  type: 'cone_created';
  coneId: string;
  /** Initial position (tree + root node) */
  head: Position;
}

export interface CreateResult_Error {
  type: 'error';
  message: string;
}


/** Currency for pricing */
export type Currency = "USD" | "EUR" | "GBP";

/** Result of cone.delete */
export type DeleteResult = DeleteResult_ConeDeleted | DeleteResult_Error;

export interface DeleteResult_ConeDeleted {
  type: 'cone_deleted';
  coneId: string;
}

export interface DeleteResult_Error {
  type: 'error';
  message: string;
}


/** Result of cone.get */
export type GetResult = GetResult_ConeData | GetResult_Error;

export interface GetResult_ConeData {
  type: 'cone_data';
  cone: ConeConfig;
}

export interface GetResult_Error {
  type: 'error';
  message: string;
}


/** Result of cone.list */
export type ListResult = ListResult_ConeList | ListResult_Error;

export interface ListResult_ConeList {
  type: 'cone_list';
  cones: ConeInfo[];
}

export interface ListResult_Error {
  type: 'error';
  message: string;
}


/** Message builder format - determines how messages are structured for the API */
export type MessageFormat = never;


/** Serializable model information */
export interface ModelExport {
  /** Model capabilities */
  capabilities: Capabilities;
  /** Model constraints */
  constraints: Constraints;
  /** Model family (e.g., "claude", "gpt") */
  family: string;
  /** Model identifier */
  id: string;
  /** Lab/organization that created the model */
  lab?: string | null;
  /** Human-readable name */
  name: string;
  /** Pricing information */
  pricing: Pricing;
  /** Service this model uses */
  service: string;
  /** Verification status */
  status: VerificationStatus;
  /** Use cases this model is suited for */
  useCases: string[];
  /** Variant (e.g., "haiku", "sonnet", "opus") */
  variant?: string | null;
  /** Version string if available */
  version?: string | null;
}

/** A position in the context tree - couples tree_id and node_id together.
This ensures we always have a valid reference into a specific tree. */
export interface Position {
  /** The specific node within the tree */
  nodeId: UUID;
  /** The tree containing this position */
  treeId: UUID;
}

export interface Pricing {
  cachedInputPer1kTokens?: number | null;
  currency?: Currency;
  inputPer1kTokens: number;
  outputPer1kTokens: number;
}

/** Serializable rate limits */
export interface RateLimitsExport {
  concurrentRequests?: number | null;
  requestsPerMinute?: number | null;
  tokensPerMinute?: number | null;
}

/** Complete registry export - all services, families, and models in one structure */
export interface RegistryExport {
  /** All model families (e.g., "claude", "gpt", "deepseek") */
  families: string[];
  /** All available models */
  models: ModelExport[];
  /** All available services */
  services: ServiceExport[];
  /** Summary statistics */
  stats: RegistryStats;
}

/** Result of cone.registry */
export type RegistryResult = RegistryResult_Registry;

export interface RegistryResult_Registry {
  type: 'registry';
}


/** Summary statistics about the registry */
export interface RegistryStats {
  /** Total number of model families */
  familyCount: number;
  /** Total number of models */
  modelCount: number;
  /** Total number of services */
  serviceCount: number;
  /** Number of unverified models */
  unverifiedCount: number;
  /** Number of verified models */
  verifiedCount: number;
}

/** Serializable service information */
export interface ServiceExport {
  /** Base URL for the API */
  baseUrl: string;
  /** Message format type */
  messageFormat: MessageFormat;
  /** Number of models using this service */
  modelCount: number;
  /** Service identifier (e.g., "openai", "anthropic") */
  name: string;
  /** Rate limits if configured */
  rateLimits?: RateLimitsExport | null;
}

/** Result of cone.set_head */
export type SetHeadResult = SetHeadResult_HeadUpdated | SetHeadResult_Error;

export interface SetHeadResult_HeadUpdated {
  type: 'head_updated';
  coneId: string;
  newHead: Position;
  oldHead: Position;
}

export interface SetHeadResult_Error {
  type: 'error';
  message: string;
}


export type UUID = string;

/** Verification status for a model configuration */
export type VerificationStatus = "verified" | "unverified" | "broken" | "deprecated" | "error" | "not_found";
