// Auto-generated by hub-codegen
// Do not edit manually

/** Type of celestial body */
export type BodyType = "star" | "planet" | "dwarf_planet" | "moon";

/** Events from solar system observations */
export type SolarEvent = SolarEvent_Body | SolarEvent_System;

/** Information about a celestial body */
export interface SolarEvent_Body {
  type: 'body';
  bodyType: BodyType;
  massKg: number;
  name: string;
  orbitalPeriodDays: number | null;
  parent: string | null;
  radiusKm: number;
}

/** System overview */
export interface SolarEvent_System {
  type: 'system';
  moonCount: number;
  planetCount: number;
  star: string;
  totalBodies: number;
}

