// Auto-generated by hub-codegen
// Do not edit manually

/** Root hub event type */
export type HyperforgeEvent = HyperforgeEvent_Status | HyperforgeEvent_Info;

export interface HyperforgeEvent_Status {
  type: 'status';
  configDir: string;
  defaultOrg: string | null;
  orgCount: number;
  version: string;
}

export interface HyperforgeEvent_Info {
  type: 'info';
  message: string;
}

