// Auto-generated by hub-codegen
// Do not edit manually

/** A pending approval request */
export interface ApprovalRequest {
  createdAt: number;
  id: string;
  input: unknown;
  resolvedAt?: number | null;
  responseMessage?: string | null;
  sessionId: string;
  status: ApprovalStatus;
  toolName: string;
  toolUseId: string;
}

/** Status of an approval request */
export type ApprovalStatus = "pending" | "approved" | "denied" | "timed_out";

export type ConfigureResult = ConfigureResult_Ok | ConfigureResult_Error;

export interface ConfigureResult_Ok {
  type: 'ok';
  mcpConfig: unknown;
}

export interface ConfigureResult_Error {
  type: 'error';
  message: string;
}


export type PendingResult = PendingResult_Ok | PendingResult_Error;

export interface PendingResult_Ok {
  type: 'ok';
  approvals: ApprovalRequest[];
}

export interface PendingResult_Error {
  type: 'error';
  message: string;
}


export type RespondResult = RespondResult_Ok | RespondResult_Error;

export interface RespondResult_Ok {
  type: 'ok';
  approvalId: string;
}

export interface RespondResult_Error {
  type: 'error';
  message: string;
}


// === Stub Types (referenced but not defined in schema) ===

/** Stub type - definition missing from IR */
export type String = unknown;
