// Auto-generated by hub-codegen
// Do not edit manually

export type SecretEvent = SecretEvent_Listed | SecretEvent_Retrieved | SecretEvent_Updated | SecretEvent_PromptRequired | SecretEvent_AcquireStarted | SecretEvent_Acquired | SecretEvent_Deleted | SecretEvent_Error;

/** List of secret keys */
export interface SecretEvent_Listed {
  type: 'listed';
  keys: SecretKey[];
  orgName: string;
}

/** Secret value retrieved */
export interface SecretEvent_Retrieved {
  type: 'retrieved';
  key: string;
  orgName: string;
  value: string;
}

/** Secret value set */
export interface SecretEvent_Updated {
  type: 'updated';
  key: string;
  orgName: string;
}

/** Prompt for secret value (interactive) */
export interface SecretEvent_PromptRequired {
  type: 'prompt_required';
  key: string;
  message: string;
  orgName: string;
}

/** Secret acquisition started */
export interface SecretEvent_AcquireStarted {
  type: 'acquire_started';
  forge: string;
  orgName: string;
}

/** Secret acquired successfully */
export interface SecretEvent_Acquired {
  type: 'acquired';
  key: string;
  orgName: string;
  source: string;
}

/** Secret deleted */
export interface SecretEvent_Deleted {
  type: 'deleted';
  key: string;
  orgName: string;
}

/** Error during secret operation */
export interface SecretEvent_Error {
  type: 'error';
  key: string | null;
  message: string;
  orgName: string;
}


export interface SecretKey {
  isSet: boolean;
  key: string;
  provider: SecretProvider;
}

export type SecretProvider = "keychain" | "env" | "file" | "pass";
