// Auto-generated by hub-codegen
// Do not edit manually

/** Stream events from bash command execution */
export type BashEvent = BashEvent_Stdout | BashEvent_Stderr | BashEvent_Exit;

/** Standard output line */
export interface BashEvent_Stdout {
  type: 'stdout';
  line: string;
}

/** Standard error line */
export interface BashEvent_Stderr {
  type: 'stderr';
  line: string;
}

/** Exit code when process completes */
export interface BashEvent_Exit {
  type: 'exit';
  code: number;
}

