// Auto-generated by hub-codegen
// Do not edit manually

/** Events from echo operations */
export type EchoEvent = EchoEvent_Echo;

/** Echo response */
export interface EchoEvent_Echo {
  type: 'echo';
  /** Number of times repeated */
  count: number;
  /** The echoed message */
  message: string;
}

