// Auto-generated by hub-codegen
// Do not edit manually

export type ResolutionSource = never;


export interface WorkspaceBinding {
  orgName: string;
  path: string;
}

export type WorkspaceEvent = WorkspaceEvent_Listed | WorkspaceEvent_Resolved | WorkspaceEvent_Bound | WorkspaceEvent_Unbound | WorkspaceEvent_NotBound | WorkspaceEvent_ReposDiscovered | WorkspaceEvent_RepoStaged | WorkspaceEvent_Error | WorkspaceEvent_DiffStarted | WorkspaceEvent_OrgDiffResult | WorkspaceEvent_OrgDiffError | WorkspaceEvent_DiffComplete | WorkspaceEvent_ImportStarted | WorkspaceEvent_OrgImportStarted | WorkspaceEvent_OrgImportComplete | WorkspaceEvent_ImportComplete | WorkspaceEvent_CloneAllStarted | WorkspaceEvent_OrgCloneAllStarted | WorkspaceEvent_OrgCloneAllComplete | WorkspaceEvent_CloneAllComplete | WorkspaceEvent_SyncStarted | WorkspaceEvent_OrgSyncStarted | WorkspaceEvent_OrgSyncComplete | WorkspaceEvent_SyncComplete;

/** List of workspace bindings */
export interface WorkspaceEvent_Listed {
  type: 'listed';
  bindings: WorkspaceBinding[];
}

/** Current workspace resolution */
export interface WorkspaceEvent_Resolved {
  type: 'resolved';
  orgName: string;
  path: string;
  source: ResolutionSource;
}

/** Workspace bound to org */
export interface WorkspaceEvent_Bound {
  type: 'bound';
  orgName: string;
  path: string;
}

/** Workspace unbound */
export interface WorkspaceEvent_Unbound {
  type: 'unbound';
  path: string;
}

/** No workspace binding found */
export interface WorkspaceEvent_NotBound {
  type: 'not_bound';
  path: string;
}

/** Repos discovered during auto-create scan */
export interface WorkspaceEvent_ReposDiscovered {
  type: 'repos_discovered';
  path: string;
  repos: string[];
}

/** Repo staged during auto-create */
export interface WorkspaceEvent_RepoStaged {
  type: 'repo_staged';
  repoName: string;
}

/** Error during workspace operation */
export interface WorkspaceEvent_Error {
  type: 'error';
  message: string;
}

/** Diff operation started for workspace */
export interface WorkspaceEvent_DiffStarted {
  type: 'diff_started';
  orgCount: number;
  workspacePath: string;
}

/** Diff result for a single org in the workspace */
export interface WorkspaceEvent_OrgDiffResult {
  type: 'org_diff_result';
  inSync: number;
  orgName: string;
  toCreate: number;
  toDelete: number;
  toUpdate: number;
}

/** Org diff failed with error */
export interface WorkspaceEvent_OrgDiffError {
  type: 'org_diff_error';
  message: string;
  orgName: string;
}

/** Diff operation completed with summary */
export interface WorkspaceEvent_DiffComplete {
  type: 'diff_complete';
  totalInSync: number;
  totalOrgs: number;
  totalToCreate: number;
  totalToDelete: number;
  totalToUpdate: number;
}

/** Workspace import operation started */
export interface WorkspaceEvent_ImportStarted {
  type: 'import_started';
  orgCount: number;
  workspacePath: string;
}

/** Started importing repos for a specific org */
export interface WorkspaceEvent_OrgImportStarted {
  type: 'org_import_started';
  orgName: string;
}

/** Completed importing repos for a specific org */
export interface WorkspaceEvent_OrgImportComplete {
  type: 'org_import_complete';
  errors: number;
  imported: number;
  orgName: string;
  skipped: number;
}

/** Workspace import operation completed */
export interface WorkspaceEvent_ImportComplete {
  type: 'import_complete';
  totalErrors: number;
  totalImported: number;
  totalSkipped: number;
}

/** Clone all operation started */
export interface WorkspaceEvent_CloneAllStarted {
  type: 'clone_all_started';
  orgCount: number;
}

/** Starting clone_all for a specific org */
export interface WorkspaceEvent_OrgCloneAllStarted {
  type: 'org_clone_all_started';
  orgName: string;
}

/** Clone all complete for a specific org */
export interface WorkspaceEvent_OrgCloneAllComplete {
  type: 'org_clone_all_complete';
  cloned: number;
  failed: number;
  orgName: string;
  skipped: number;
}

/** Clone all operation complete for all orgs */
export interface WorkspaceEvent_CloneAllComplete {
  type: 'clone_all_complete';
  totalCloned: number;
  totalFailed: number;
  totalSkipped: number;
}

/** Sync operation started for workspace */
export interface WorkspaceEvent_SyncStarted {
  type: 'sync_started';
  orgCount: number;
  workspacePath: string;
}

/** Sync started for a specific org within workspace sync */
export interface WorkspaceEvent_OrgSyncStarted {
  type: 'org_sync_started';
  orgName: string;
}

/** Sync completed for a specific org within workspace sync */
export interface WorkspaceEvent_OrgSyncComplete {
  type: 'org_sync_complete';
  failed: number;
  orgName: string;
  synced: number;
  unchanged: number;
}

/** Sync operation completed for entire workspace */
export interface WorkspaceEvent_SyncComplete {
  type: 'sync_complete';
  totalFailed: number;
  totalSynced: number;
  totalUnchanged: number;
  workspacePath: string;
}

