// Auto-generated by hub-codegen
// Do not edit manually

import type { UUID } from '../cone/types';

/** Events emitted by Arbor operations */
export type ArborEvent = ArborEvent_TreeCreated | ArborEvent_TreeDeleted | ArborEvent_TreeUpdated | ArborEvent_TreeList | ArborEvent_TreeClaimed | ArborEvent_TreeReleased | ArborEvent_TreeScheduledDeletion | ArborEvent_TreeArchived | ArborEvent_TreeRefs | ArborEvent_NodeCreated | ArborEvent_NodeUpdated | ArborEvent_NodeDeleted | ArborEvent_NodeClaimed | ArborEvent_NodeReleased | ArborEvent_NodeScheduledDeletion | ArborEvent_NodeArchived | ArborEvent_NodeRefs | ArborEvent_TreeData | ArborEvent_TreeSkeleton | ArborEvent_NodeData | ArborEvent_NodeChildren | ArborEvent_NodeParent | ArborEvent_ContextPath | ArborEvent_ContextPathData | ArborEvent_ContextHandles | ArborEvent_ContextLeaves | ArborEvent_TreesScheduled | ArborEvent_NodesScheduled | ArborEvent_TreesArchived | ArborEvent_TreeRender;

export interface ArborEvent_TreeCreated {
  type: 'tree_created';
  treeId: UUID;
}

export interface ArborEvent_TreeDeleted {
  type: 'tree_deleted';
  treeId: UUID;
}

export interface ArborEvent_TreeUpdated {
  type: 'tree_updated';
  treeId: UUID;
}

export interface ArborEvent_TreeList {
  type: 'tree_list';
  treeIds: UUID[];
}

export interface ArborEvent_TreeClaimed {
  type: 'tree_claimed';
  newCount: number;
  ownerId: string;
  treeId: UUID;
}

export interface ArborEvent_TreeReleased {
  type: 'tree_released';
  newCount: number;
  ownerId: string;
  treeId: UUID;
}

export interface ArborEvent_TreeScheduledDeletion {
  type: 'tree_scheduled_deletion';
  scheduledAt: number;
  treeId: UUID;
}

export interface ArborEvent_TreeArchived {
  type: 'tree_archived';
  archivedAt: number;
  treeId: UUID;
}

export interface ArborEvent_TreeRefs {
  type: 'tree_refs';
  refs: ResourceRefs;
  treeId: UUID;
}

export interface ArborEvent_NodeCreated {
  type: 'node_created';
  nodeId: UUID;
  parent: UUID | null;
  treeId: UUID;
}

export interface ArborEvent_NodeUpdated {
  type: 'node_updated';
  newId: UUID;
  oldId: UUID;
  treeId: UUID;
}

export interface ArborEvent_NodeDeleted {
  type: 'node_deleted';
  nodeId: UUID;
  treeId: UUID;
}

export interface ArborEvent_NodeClaimed {
  type: 'node_claimed';
  newCount: number;
  nodeId: UUID;
  ownerId: string;
  treeId: UUID;
}

export interface ArborEvent_NodeReleased {
  type: 'node_released';
  newCount: number;
  nodeId: UUID;
  ownerId: string;
  treeId: UUID;
}

export interface ArborEvent_NodeScheduledDeletion {
  type: 'node_scheduled_deletion';
  nodeId: UUID;
  scheduledAt: number;
  treeId: UUID;
}

export interface ArborEvent_NodeArchived {
  type: 'node_archived';
  archivedAt: number;
  nodeId: UUID;
  treeId: UUID;
}

export interface ArborEvent_NodeRefs {
  type: 'node_refs';
  nodeId: UUID;
  refs: ResourceRefs;
  treeId: UUID;
}

export interface ArborEvent_TreeData {
  type: 'tree_data';
  tree: Tree;
}

export interface ArborEvent_TreeSkeleton {
  type: 'tree_skeleton';
  skeleton: TreeSkeleton;
}

export interface ArborEvent_NodeData {
  type: 'node_data';
  node: Node;
  treeId: UUID;
}

export interface ArborEvent_NodeChildren {
  type: 'node_children';
  children: UUID[];
  nodeId: UUID;
  treeId: UUID;
}

export interface ArborEvent_NodeParent {
  type: 'node_parent';
  nodeId: UUID;
  parent: UUID | null;
  treeId: UUID;
}

export interface ArborEvent_ContextPath {
  type: 'context_path';
  path: UUID[];
  treeId: UUID;
}

export interface ArborEvent_ContextPathData {
  type: 'context_path_data';
  nodes: Node[];
  treeId: UUID;
}

export interface ArborEvent_ContextHandles {
  type: 'context_handles';
  handles: Handle[];
  treeId: UUID;
}

export interface ArborEvent_ContextLeaves {
  type: 'context_leaves';
  leaves: UUID[];
  treeId: UUID;
}

export interface ArborEvent_TreesScheduled {
  type: 'trees_scheduled';
  treeIds: UUID[];
}

export interface ArborEvent_NodesScheduled {
  type: 'nodes_scheduled';
  nodeIds: UUID[];
  treeId: UUID;
}

export interface ArborEvent_TreesArchived {
  type: 'trees_archived';
  treeIds: UUID[];
}

export interface ArborEvent_TreeRender {
  type: 'tree_render';
  render: string;
  treeId: UUID;
}


/** Handle pointing to external data with versioning

Display format: `{plugin_id}@{version}::{method}:meta[0]:meta[1]:...`

Examples:
- `550e8400-e29b-41d4-a716-446655440000@1.0.0::chat:msg-123:user:bob`
- `123e4567-e89b-12d3-a456-426614174000@1.0.0::execute:cmd-789` */
export interface Handle {
  /** Metadata parts - variable length list of strings
For messages: typically [message_uuid, role, optional_extra...] */
  meta?: string[];
  /** Creation method that produced this handle (e.g., "chat", "execute") */
  method: string;
  /** Stable plugin instance identifier (UUID) */
  pluginId: string;
  /** Plugin version (semantic version: "MAJOR.MINOR.PATCH")
Used for schema/type lookup */
  version: string;
}

/** A node in the conversation tree */
export interface Node {
  /** Archived timestamp (Unix seconds) */
  archivedAt?: number | null;
  /** Child nodes (in order) */
  children: UUID[];
  /** Creation timestamp (Unix seconds) */
  createdAt: number;
  /** Node data (handle or built-in) */
  data: NodeType;
  /** Unique identifier for this node */
  id: UUID;
  /** Optional metadata */
  metadata?: unknown;
  /** Parent node (None for root) */
  parent?: UUID | null;
  /** Reference count information */
  refs?: ResourceRefs | null;
  /** Scheduled deletion timestamp (Unix seconds) */
  scheduledDeletionAt?: number | null;
  /** Reference counting state */
  state?: ResourceState | null;
}

/** Lightweight node representation (just structure, no data) */
export interface NodeSkeleton {
  children: UUID[];
  id: UUID;
  /** Type indicator (but not the actual data) */
  nodeType: string;
  parent?: UUID | null;
}

/** Node type discriminator */
export type NodeType = NodeType_Text | NodeType_External;

/** Built-in text node (data stored in Arbor) */
export interface NodeType_Text {
  type: 'text';
  content: string;
}

/** External data reference */
export interface NodeType_External {
  type: 'external';
  handle: Handle;
}


/** Reference counting information for a resource */
export interface ResourceRefs {
  /** Who owns references (owner_id -> count) */
  owners: Record<string, unknown>;
  /** Total reference count */
  refCount: number;
}

/** Resource state in deletion lifecycle */
export type ResourceState = "active" | "scheduled_delete" | "archived";

/** A conversation tree */
export interface Tree {
  /** Archived timestamp (Unix seconds) */
  archivedAt?: number | null;
  /** Creation timestamp (Unix seconds) */
  createdAt: number;
  /** Unique identifier for this tree */
  id: UUID;
  /** Optional tree-level metadata (name, description, etc.) */
  metadata?: unknown;
  /** All nodes in the tree (NodeId -> Node) */
  nodes: Record<string, unknown>;
  /** Reference count information */
  refs?: ResourceRefs | null;
  /** Root node ID */
  root: UUID;
  /** Scheduled deletion timestamp (Unix seconds) */
  scheduledDeletionAt?: number | null;
  /** Reference counting state */
  state?: ResourceState | null;
  /** Last modified timestamp (Unix seconds) */
  updatedAt: number;
}

/** Lightweight tree structure */
export interface TreeSkeleton {
  id: UUID;
  nodes: Record<string, unknown>;
  root: UUID;
  state?: ResourceState | null;
}
